feat: add 'broken' state to scenario, add protocol to unstable_test rule
Signed-off-by: aeddi <antoine.e.b@gmail.com>

diff --git a/go/Makefile b/go/Makefile
--- a/go/Makefile
+++ b/go/Makefile
@@ -77,7 +77,10 @@ go.unstable-tests:
 	@for test in `cd ./pkg/bertymessenger; go test -list . | grep -E "^TestUnstable"`; do \
 	  (set -xe; DONT_SKIP_UNSTABLE=1 retry -m 10 ./pkg/bertymessenger/tests.bin -test.count 1 -test.run "^$$test\$$" 2>/dev/null || echo "  $$test failed 10/10 times"); \
 	done
-	@# FIXME: support bertyprotocol
+	cd ./pkg/bertyprotocol && go test -c -o ./tests.bin .
+	@for test in `cd ./pkg/bertyprotocol; go test -list . | grep -E "^TestScenario_"`; do \
+	  (set -xe; TEST_FILTER='unstable' retry -m 10 ./pkg/bertyprotocol/tests.bin -test.count 1 -test.run "^$$test\$$" 2>/dev/null || echo "  $$test failed 10/10 times"); \
+	done
 
 .PHONY: go.install
 go.install: pb.generate
