chore: check minimal go version
    foot@bar:~$ for version in 1.11 1.12 1.13 1.13.1 1.14 1.14.1 1.15 1.15.2; do (echo "== go$version"; gvm use go$version && make install && berty version; echo); done
    == go1.11
    Now using version go1.11.13
    error: Golang version is not supported. Please use 1.14 or more recent.
    Makefile:129: recipe for target 'validate-go-version' failed
    make: *** [validate-go-version] Error 1

    == go1.12
    Now using version go1.12
    error: Golang version is not supported. Please use 1.14 or more recent.
    Makefile:129: recipe for target 'validate-go-version' failed
    make: *** [validate-go-version] Error 1

    == go1.13
    Now using version go1.13
    error: Golang version is not supported. Please use 1.14 or more recent.
    Makefile:129: recipe for target 'validate-go-version' failed
    make: *** [validate-go-version] Error 1

    == go1.13.1
    Now using version go1.13.1
    error: Golang version is not supported. Please use 1.14 or more recent.
    Makefile:129: recipe for target 'validate-go-version' failed
    make: *** [validate-go-version] Error 1

    == go1.14
    Now using version go1.14
    GO111MODULE=on go install -ldflags="-X berty.tech/berty/v2/go/pkg/bertymessenger.VcsRef=`git rev-parse --short HEAD` -X berty.tech/berty/v2/go/pkg/bertymessenger.Version=`git describe --tags --always`" -v ./cmd/...
    git version  v2.141.4-4-ge7155f74
    vcs          https://github.com/berty/berty/commits/e7155f74
    go           go1.14

    == go1.14.1
    Now using version go1.14.1
    GO111MODULE=on go install -ldflags="-X berty.tech/berty/v2/go/pkg/bertymessenger.VcsRef=`git rev-parse --short HEAD` -X berty.tech/berty/v2/go/pkg/bertymessenger.Version=`git describe --tags --always`" -v ./cmd/...
    git version  v2.141.4-4-ge7155f74
    vcs          https://github.com/berty/berty/commits/e7155f74
    go           go1.14.1

    == go1.15
    Now using version go1.15
    GO111MODULE=on go install -ldflags="-X berty.tech/berty/v2/go/pkg/bertymessenger.VcsRef=`git rev-parse --short HEAD` -X berty.tech/berty/v2/go/pkg/bertymessenger.Version=`git describe --tags --always`" -v ./cmd/...
    git version  v2.141.4-4-ge7155f74
    vcs          https://github.com/berty/berty/commits/e7155f74
    go           go1.15

    == go1.15.2
    Now using version go1.15.2
    GO111MODULE=on go install -ldflags="-X berty.tech/berty/v2/go/pkg/bertymessenger.VcsRef=`git rev-parse --short HEAD` -X berty.tech/berty/v2/go/pkg/bertymessenger.Version=`git describe --tags --always`" -v ./cmd/...
    git version  v2.141.4-4-ge7155f74
    vcs          https://github.com/berty/berty/commits/e7155f74
    go           go1.15.2

Signed-off-by: Manfred Touron <94029+moul@users.noreply.github.com>

diff --git a/go/Makefile b/go/Makefile
--- a/go/Makefile
+++ b/go/Makefile
@@ -124,6 +124,19 @@ print-%:
 	@echo $* = $($*)
 
 
+minimum_go_minor_version = 14
+validate-go-version:
+	@if [ ! "x`$(GO) version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -f1`" = "x1" ]; then \
+		echo "error: Golang version should be \"1.x\". Please use 1.$(minimum_go_minor_version) or more recent."; \
+		exit 1; \
+	fi
+	@if [ `$(GO) version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -f2` -lt $(minimum_go_minor_version) ]; then \
+		echo "error: Golang version is not supported. Please use 1.$(minimum_go_minor_version) or more recent."; \
+		exit 1; \
+	fi
+.PHONY: validate-go-version
+
+
 ##
 ## Code gen
 ##
@@ -133,7 +146,7 @@ protos_src := $(wildcard ../api/*.proto) $(wildcard ../api/go-internal/*.proto)
 gen_src := $(protos_src) Makefile
 gen_sum := gen.sum
 protoc_opts := -I ../api:`go list -m -f {{.Dir}} github.com/grpc-ecosystem/grpc-gateway`/third_party/googleapis:`go list -m -f {{.Dir}} github.com/gogo/protobuf`:/protobuf
-pb.generate: gen.sum
+pb.generate: gen.sum validate-go-version
 $(gen_sum): $(gen_src)
 	$(call check-program, shasum docker $(GO))
 	@shasum $(gen_src) | sort -k 2 > $(gen_sum).tmp
