Chore/update kubo@v0.29.0 + weshnet (#4866)
* chore: remove gogoproto

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: remove gogoproto, use latest weshnet

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* fix: tests

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: disable nopfs kubo plugin in encrypted repo

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: rename BertyID to BertyId

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: fix ci lint

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* fix: unitest

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: fix unitest + goreleaser deprecated flag

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: fix CI

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: add LazyVim in ssh-runner Github Action workflow

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: use latest weshnet that should fix TestFlow in bertyaccount

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: use remove deprecated --skip-publish flag in goreleaser

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: update goreleaser config to v2

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* fix: Flipper for Xcode 15.3 or above

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* fix: Remove Flipper on iOS

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* fix: replace quic by quic-v1

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: use latest weshnet

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* fix: change rdvp topic into valid UTF-8

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: use berty.tech/weshnet/v2

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

* chore: remove replace in go.mod for berty.tech/weshnet

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

---------

Signed-off-by: D4ryl00 <d4ryl00@gmail.com>

diff --git a/js/ios/berty.yaml b/js/ios/berty.yaml
--- a/js/ios/berty.yaml
+++ b/js/ios/berty.yaml
@@ -2,12 +2,11 @@ name: Berty
 
 options:
   deploymentTarget:
-    iOS: "12.0"
+    iOS: '12.0'
   usesTabs: false
   tabWidth: 2
   indentWidth: 2
   defaultConfig: Debug
-
 
 fileGroups:
   - Berty/main.jsbundle # required by react-native
@@ -70,17 +69,17 @@ settings:
     SWIFT_OBJC_BRIDGING_HEADER: Berty/Berty-Bridging-Header.h
     CLANG_ENABLE_MODULES: true
     OTHER_LDFLAGS:
-    - $(inherited)
-    - -ObjC
-    - -lc++
+      - $(inherited)
+      - -ObjC
+      - -lc++
     LD_RUNPATH_SEARCH_PATHS:
-    - /usr/lib/swift
-    - $(inherited)
+      - /usr/lib/swift
+      - $(inherited)
     LIBRARY_SEARCH_PATHS:
-    - $(SDKROOT)/usr/lib/swift
-    - $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
-    - $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
-    - $(inherited)
+      - $(SDKROOT)/usr/lib/swift
+      - $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
+      - $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
+      - $(inherited)
     GCC_C_LANGUAGE_STANDARD: gnu99
     CLANG_CXX_LANGUAGE_STANDARD: gnu++0x
     CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
@@ -93,14 +92,14 @@ settings:
       GCC_SYMBOLS_PRIVATE_EXTERN: false
       MTL_ENABLE_DEBUG_INFO: true
       GCC_PREPROCESSOR_DEFINITIONS:
-      - $(inherited)
-      - FB_SONARKIT_ENABLED=1
-      - DEBUG=1
+        - $(inherited)
+        - FB_SONARKIT_ENABLED=1
+        - DEBUG=1
     release:
       COPY_PHASE_STRIP: true
       MTL_ENABLE_DEBUG_INFO: false
       GCC_PREPROCESSOR_DEFINITIONS:
-      - $(inherited)
+        - $(inherited)
 
 targets:
   Berty:
@@ -128,7 +127,7 @@ targets:
           ASSETCATALOG_COMPILER_APPICON_NAME: AppIconDebug
           CODE_SIGN_ENTITLEMENTS: Entitlements/Dev.entitlements
           APP_GROUP_ID: group.tech.berty.dev
-          OTHER_SWIFT_FLAGS: "-D CFG_DEBUG -D DEBUG_LOGS $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_DEBUG -D DEBUG_LOGS $(inherited)'
         AppStore:
           DEVELOPMENT_TEAM: WMBQ84HN4T
           PRODUCT_NAME: Berty
@@ -136,7 +135,7 @@ targets:
           ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
           CODE_SIGN_ENTITLEMENTS: Entitlements/Prod.entitlements
           APP_GROUP_ID: group.tech.berty
-          OTHER_SWIFT_FLAGS: "-D CFG_APPSTORE $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_APPSTORE $(inherited)'
         Staff:
           DEVELOPMENT_TEAM: WMBQ84HN4T
           PRODUCT_NAME: Berty Staff
@@ -144,7 +143,7 @@ targets:
           ASSETCATALOG_COMPILER_APPICON_NAME: AppIconStaff
           CODE_SIGN_ENTITLEMENTS: Entitlements/Dev.entitlements
           APP_GROUP_ID: group.tech.berty.dev
-          OTHER_SWIFT_FLAGS: "-D CFG_STAFF -D DEBUG_LOGS $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_STAFF -D DEBUG_LOGS $(inherited)'
         Yolo:
           DEVELOPMENT_TEAM: GR5463T564
           PRODUCT_NAME: 'Berty ${YOLO_SUFFIX}'
@@ -152,63 +151,63 @@ targets:
           ASSETCATALOG_COMPILER_APPICON_NAME: AppIconYolo
           CODE_SIGN_ENTITLEMENTS: Entitlements/Entreprise.entitlements
           APP_GROUP_ID: group.tech.berty.entreprise
-          OTHER_SWIFT_FLAGS: "-D CFG_YOLO -D DEBUG_LOGS $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_YOLO -D DEBUG_LOGS $(inherited)'
 
     sources:
-    - Berty
-    - NotificationService/Common.swift
-    - path: ../packages/assets/font
-      name: Fonts
-      group: Resources
-    - path: ../packages/assets/sound
-      name: Sounds
-      group: Resources
+      - Berty
+      - NotificationService/Common.swift
+      - path: ../packages/assets/font
+        name: Fonts
+        group: Resources
+      - path: ../packages/assets/sound
+        name: Sounds
+        group: Resources
     dependencies:
-    - target: NotificationService
-      codeSign: false
-      embed: true
-    - framework: JavascriptCore.framework
-      embed: false
-      link: false
-    - sdk: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/MultipeerConnectivity.framework
-      root: DEVELOPER_DIR
-      link: true
-    - sdk: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreBluetooth.framework
-      root: DEVELOPER_DIR
-      link: true
-    - sdk: usr/lib/libresolv.tbd
-      root: SDKROOT
-      link: true
-    - framework: ./Frameworks/Bertybridge.xcframework
-      embed: false
-    - framework: "${SRCROOT}/../node_modules/expo-file-system/ios/EXFileSystem.xcframework"
-      embed: false
-    - framework: "${SRCROOT}/../node_modules/expo-camera/ios/EXCamera.xcframework"
-      embed: false
+      - target: NotificationService
+        codeSign: false
+        embed: true
+      - framework: JavascriptCore.framework
+        embed: false
+        link: false
+      - sdk: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/MultipeerConnectivity.framework
+        root: DEVELOPER_DIR
+        link: true
+      - sdk: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreBluetooth.framework
+        root: DEVELOPER_DIR
+        link: true
+      - sdk: usr/lib/libresolv.tbd
+        root: SDKROOT
+        link: true
+      - framework: ./Frameworks/Bertybridge.xcframework
+        embed: false
+      - framework: '${SRCROOT}/../node_modules/expo-file-system/ios/EXFileSystem.xcframework'
+        embed: false
+      - framework: '${SRCROOT}/../node_modules/expo-camera/ios/EXCamera.xcframework'
+        embed: false
 
     preBuildScripts:
-    - name: Start Packager
-      script: |
-        export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
-        echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
-        if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
-          if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
-            if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
-              echo "Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
-              exit 2
+      - name: Start Packager
+        script: |
+          export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
+          echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
+          if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
+            if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
+              if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
+                echo "Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
+                exit 2
+              fi
+            else
+              open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "Can't start packager automatically"
             fi
-          else
-            open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "Can't start packager automatically"
           fi
-        fi
-      showEnvVars: false
+        showEnvVars: false
 
     postBuildScripts:
-    - name: Bundle React Native code and images
-      script: |
-        export NODE_BINARY="$(zsh -ilc 'asdf which node' 2> /dev/null || echo node)"
-        export ENTRY_FILE=index.ts
-        ../node_modules/react-native/scripts/react-native-xcode.sh
+      - name: Bundle React Native code and images
+        script: |
+          export NODE_BINARY="$(zsh -ilc 'asdf which node' 2> /dev/null || echo node)"
+          export ENTRY_FILE=index.ts
+          ../node_modules/react-native/scripts/react-native-xcode.sh
 
   NotificationService:
     type: app-extension
@@ -230,39 +229,39 @@ targets:
           DEVELOPMENT_TEAM: WMBQ84HN4T
           CODE_SIGN_ENTITLEMENTS: Entitlements/DevNS.entitlements
           APP_GROUP_ID: group.tech.berty.dev
-          OTHER_SWIFT_FLAGS: "-D CFG_DEBUG $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_DEBUG $(inherited)'
         AppStore:
           PRODUCT_BUNDLE_IDENTIFIER: tech.berty.ios.NotificationService
           DEVELOPMENT_TEAM: WMBQ84HN4T
           CODE_SIGN_ENTITLEMENTS: Entitlements/ProdNS.entitlements
           APP_GROUP_ID: group.tech.berty
-          OTHER_SWIFT_FLAGS: "-D CFG_APPSTORE $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_APPSTORE $(inherited)'
         Staff:
           PRODUCT_BUNDLE_IDENTIFIER: tech.berty.ios.staff.NotificationService
           DEVELOPMENT_TEAM: WMBQ84HN4T
           CODE_SIGN_ENTITLEMENTS: Entitlements/DevNS.entitlements
           APP_GROUP_ID: group.tech.berty.dev
-          OTHER_SWIFT_FLAGS: "-D CFG_STAFF $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_STAFF $(inherited)'
         Yolo:
           PRODUCT_BUNDLE_IDENTIFIER: tech.berty.ios.yolo.NotificationService
           DEVELOPMENT_TEAM: GR5463T564
           CODE_SIGN_ENTITLEMENTS: Entitlements/EntrepriseNS.entitlements
           APP_GROUP_ID: group.tech.berty.entreprise
-          OTHER_SWIFT_FLAGS: "-D CFG_YOLO $(inherited)"
+          OTHER_SWIFT_FLAGS: '-D CFG_YOLO $(inherited)'
     sources:
-        - NotificationService
-        - Localization
-        - Berty/Sources/RootDir/RootDir.swift
-        - Berty/Sources/Bridge/KeystoreDriver.swift
+      - NotificationService
+      - Localization
+      - Berty/Sources/RootDir/RootDir.swift
+      - Berty/Sources/Bridge/KeystoreDriver.swift
 
     dependencies:
       - framework: ./Frameworks/Bertypush.xcframework
         embed: false
-      - framework: "${PODS_ROOT}/OpenSSL-Universal/Frameworks/OpenSSL.xcframework"
+      - framework: '${PODS_ROOT}/OpenSSL-Universal/OpenSSL.xcframework'
         embed: false
       - sdk: usr/lib/libresolv.tbd
         root: SDKROOT
         link: true
 
 include:
-- info.yaml
+  - info.yaml
